import json,copy
B={'start_date':'2023-07-17','end_date':'2026-07-24','initial_cash':10000,'monthly_injection':0,'weights':{'quality':25,'cost':20,'manager':20,'momentum':15,'smart_money':20},'min_score':3.3,'no_stop_loss':True,'take_profit_pct':1000,'profit_mode':'half','cost_penalty':0,'min_consensus':2,'fund_type_filter':'all','momentum_sell':0,'max_candidates_per_day':0,'max_holdings':8,'kelly_cap':0.35,'smart_swap':True,'smart_swap_margin':1.0,'smart_swap_min_hold_days':30,'dynamic_max_holdings':True,'max_holdings_bull_mult':1.5,'max_holdings_bear_mult':0.6}
S=[]
def a(n,o):
 c=copy.deepcopy(B);c.update(o);S.append({'name':n,'desc':'','config':c})
for d in [0.01,0.02,0.03]:
 for i in [1000,2000,3000]: a(f'V6A_A1_drop{d}_inj{i}',{'contrarian_buy_drop':d,'monthly_injection':i})
a('V6A_A1_champ_inj3k_kc045',{'contrarian_buy_drop':0.03,'monthly_injection':3000,'kelly_cap':0.45})
a('V6A_A1_noinj_inj2k',{'monthly_injection':2000})
for d in [0.01,0.02,0.03]: a(f'V6A_B1_drop{d}_pyramid',{'contrarian_buy_drop':d,'pyramiding_enabled':True})
a('V6A_B1_champ_pyr_inj2k',{'contrarian_buy_drop':0.03,'pyramiding_enabled':True,'monthly_injection':2000})
a('V6A_B1_champ_pyr_inj2k_kc045',{'contrarian_buy_drop':0.03,'pyramiding_enabled':True,'monthly_injection':2000,'kelly_cap':0.45})
a('V6A_B1_nodrop_pyr_inj2k',{'pyramiding_enabled':True,'monthly_injection':2000})
for d in [0.01,0.02,0.03]: a(f'V6A_C1_drop{d}_trail20_8',{'contrarian_buy_drop':d,'trailing_tp_activate':20,'trailing_tp_drawdown':8})
a('V6A_C1_champ_trail15_10',{'contrarian_buy_drop':0.03,'trailing_tp_activate':15,'trailing_tp_drawdown':10})
a('V6A_C1_champ_trail30_12',{'contrarian_buy_drop':0.03,'trailing_tp_activate':30,'trailing_tp_drawdown':12})
a('V6A_C1_equal_trail20_10',{'equal_allocate':True,'trailing_tp_activate':20,'trailing_tp_drawdown':10})
a('V6A_C1_champ_trail20_8_inj2k',{'contrarian_buy_drop':0.03,'trailing_tp_activate':20,'trailing_tp_drawdown':8,'monthly_injection':2000})
for d in [0.02,0.03]: a(f'V6A_D1_drop{d}_steptp',{'contrarian_buy_drop':d,'step_take_profit':True})
a('V6A_D1_champ_steptp_2040_60',{'contrarian_buy_drop':0.03,'step_take_profit':True,'step_tp_levels':[[20,0.3],[40,0.3],[60,0.4]]})
a('V6A_D1_champ_steptp_inj2k',{'contrarian_buy_drop':0.03,'step_take_profit':True,'monthly_injection':2000})
a('V6A_D1_equal_steptp',{'equal_allocate':True,'step_take_profit':True})
for dy in [5,10,15]: a(f'V6A_E1_champ_momdecay{dy}',{'contrarian_buy_drop':0.03,'mom_decay_days':dy})
a('V6A_E1_champ_momdecay10_trail20',{'contrarian_buy_drop':0.03,'mom_decay_days':10,'trailing_tp_activate':20,'trailing_tp_drawdown':10})
a('V6A_F1_champ_buyback',{'contrarian_buy_drop':0.03,'enable_buy_back':True})
a('V6A_F1_champ_buyback_ts15',{'contrarian_buy_drop':0.03,'enable_buy_back':True,'trailing_stop_pct':15})
a('V6A_F1_equal_buyback',{'equal_allocate':True,'enable_buy_back':True})
a('V6A_G1_champ_dynkelly',{'contrarian_buy_drop':0.03,'regime_specific':True,'kelly_cap_bull':0.50,'kelly_cap_bear':0.15})
a('V6A_G1_champ_dk_inj2k',{'contrarian_buy_drop':0.03,'regime_specific':True,'kelly_cap_bull':0.50,'kelly_cap_bear':0.15,'monthly_injection':2000})
a('V6A_G1_equal_dynkelly',{'equal_allocate':True,'regime_specific':True,'kelly_cap_bull':0.50,'kelly_cap_bear':0.15})
a('V6A_G1_champ_dk_pyr',{'contrarian_buy_drop':0.03,'regime_specific':True,'kelly_cap_bull':0.50,'kelly_cap_bear':0.15,'pyramiding_enabled':True})
a('V6A_H1_champ_full',{'contrarian_buy_drop':0.03,'monthly_injection':2000,'pyramiding_enabled':True,'trailing_tp_activate':20,'trailing_tp_drawdown':10,'regime_specific':True,'kelly_cap_bull':0.45,'kelly_cap_bear':0.15})
a('V6A_H1_equal_full',{'equal_allocate':True,'monthly_injection':2000,'pyramiding_enabled':True,'trailing_tp_activate':20,'trailing_tp_drawdown':10,'regime_specific':True,'kelly_cap_bull':0.45,'kelly_cap_bear':0.15})
a('V6A_H1_drop02_full',{'contrarian_buy_drop':0.02,'monthly_injection':2000,'pyramiding_enabled':True,'trailing_tp_activate':25,'trailing_tp_drawdown':12,'regime_specific':True,'kelly_cap_bull':0.50,'kelly_cap_bear':0.15})
a('V6A_H1_steptp_pyr_inj',{'contrarian_buy_drop':0.03,'monthly_injection':2000,'pyramiding_enabled':True,'step_take_profit':True,'regime_specific':True,'kelly_cap_bull':0.45,'kelly_cap_bear':0.15})
a('V6A_Z0_baseline',{})
a('V6A_Z1_champion',{'contrarian_buy_drop':0.03})
json.dump(S,open('backtest/v6a_sweep_configs.json','w',encoding='utf-8'),ensure_ascii=False,indent=2)
print(f'V6A total: {len(S)}')
