import json,copy
B={'start_date':'2023-07-17','end_date':'2026-07-24','initial_cash':10000,'monthly_injection':0,'weights':{'quality':25,'cost':20,'manager':20,'momentum':15,'smart_money':20},'min_score':3.3,'no_stop_loss':True,'take_profit_pct':1000,'profit_mode':'half','cost_penalty':0,'min_consensus':2,'fund_type_filter':'all','momentum_sell':0,'max_candidates_per_day':0,'max_holdings':8,'kelly_cap':0.35,'smart_swap':True,'smart_swap_margin':1.0,'smart_swap_min_hold_days':30,'dynamic_max_holdings':True,'max_holdings_bull_mult':1.5,'max_holdings_bear_mult':0.6}
S=[]
def a(n,o):
 c=copy.deepcopy(B);c.update(o);S.append({'name':n,'desc':'','config':c})
for d in [0.01,0.02,0.03]: a(f'V6C_A1_drop{d}_ml',{'contrarian_buy_drop':d,'ml_signal':True})
for d in [0.02,0.03]: a(f'V6C_A1_drop{d}_ml_w05',{'contrarian_buy_drop':d,'ml_signal':True,'ml_weight':0.5})
for d in [0.02,0.03]: a(f'V6C_A1_drop{d}_ml_w15',{'contrarian_buy_drop':d,'ml_signal':True,'ml_weight':1.5})
a('V6C_A1_equal_ml',{'equal_allocate':True,'ml_signal':True})
a('V6C_A1_champ_ml_retrain30',{'contrarian_buy_drop':0.03,'ml_signal':True,'ml_retrain_days':30})
a('V6C_A1_champ_ml_retrain60',{'contrarian_buy_drop':0.03,'ml_signal':True,'ml_retrain_days':60})
a('V6C_A1_champ_ml_cold05',{'contrarian_buy_drop':0.03,'ml_signal':True,'ml_cold_start_drop':0.5})
a('V6C_A1_champ_ml_cold10',{'contrarian_buy_drop':0.03,'ml_signal':True,'ml_cold_start_drop':1.0})
for d in [0.02,0.03]: a(f'V6C_B1_drop{d}_lgb_buy07',{'contrarian_buy_drop':d,'lgb_predictor':True,'lgb_buy_stop_threshold':0.7})
for d in [0.02,0.03]: a(f'V6C_B1_drop{d}_lgb_buy08',{'contrarian_buy_drop':d,'lgb_predictor':True,'lgb_buy_stop_threshold':0.8})
a('V6C_B1_champ_lgb_crash003',{'contrarian_buy_drop':0.03,'lgb_predictor':True,'lgb_crash_threshold':-0.03})
a('V6C_B1_champ_lgb_crash008',{'contrarian_buy_drop':0.03,'lgb_predictor':True,'lgb_crash_threshold':-0.08})
a('V6C_B1_champ_lgb_sell05',{'contrarian_buy_drop':0.03,'lgb_predictor':True,'lgb_sell_threshold':0.5})
a('V6C_B1_champ_lgb_sell07',{'contrarian_buy_drop':0.03,'lgb_predictor':True,'lgb_sell_threshold':0.7})
a('V6C_B1_equal_lgb_buy07',{'equal_allocate':True,'lgb_predictor':True,'lgb_buy_stop_threshold':0.7})
a('V6C_B1_champ_lgb_retrain30',{'contrarian_buy_drop':0.03,'lgb_predictor':True,'lgb_retrain_days':30})
a('V6C_B1_champ_lgb_retrain60',{'contrarian_buy_drop':0.03,'lgb_predictor':True,'lgb_retrain_days':60})
a('V6C_C1_champ_ml_lgb',{'contrarian_buy_drop':0.03,'ml_signal':True,'lgb_predictor':True,'lgb_buy_stop_threshold':0.7})
a('V6C_C1_champ_ml_lgb_sell05',{'contrarian_buy_drop':0.03,'ml_signal':True,'lgb_predictor':True,'lgb_sell_threshold':0.5})
a('V6C_C1_equal_ml_lgb',{'equal_allocate':True,'ml_signal':True,'lgb_predictor':True,'lgb_buy_stop_threshold':0.7})
a('V6C_C1_champ_ml_lgb_inj2k',{'contrarian_buy_drop':0.03,'ml_signal':True,'lgb_predictor':True,'lgb_buy_stop_threshold':0.7,'monthly_injection':2000})
a('V6C_C1_champ_ml_lgb_trail20',{'contrarian_buy_drop':0.03,'ml_signal':True,'lgb_predictor':True,'lgb_buy_stop_threshold':0.7,'trailing_tp_activate':20,'trailing_tp_drawdown':10})
a('V6C_C1_champ_ml_lgb_pyr',{'contrarian_buy_drop':0.03,'ml_signal':True,'lgb_predictor':True,'lgb_buy_stop_threshold':0.7,'pyramiding_enabled':True})
a('V6C_C1_champ_ml_lgb_full',{'contrarian_buy_drop':0.03,'ml_signal':True,'lgb_predictor':True,'lgb_buy_stop_threshold':0.7,'lgb_sell_threshold':0.5,'monthly_injection':2000,'trailing_tp_activate':20,'trailing_tp_drawdown':10,'pyramiding_enabled':True})
a('V6C_Z0_baseline',{})
a('V6C_Z1_champion',{'contrarian_buy_drop':0.03})
json.dump(S,open('backtest/v6c_sweep_configs.json','w',encoding='utf-8'),ensure_ascii=False,indent=2)
print(f'V6C total: {len(S)}')
